export const seoKeywords = [
  "Sania Sadaqat",
  "ML Engineer",
  "AI Engineer",
  "Machine Learning Engineer",
  "Artificial Intelligence Engineer",
  "Data Scientist",
  "Deep Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "AI Researcher",
  "ML Researcher",
  "Data Analyst",
  "AI Developer",
  "ML Developer",
  "Python Developer",
  "TensorFlow Developer",
  "PyTorch Developer",
  "Keras Developer",
  "Scikit-Learn Developer",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "AI Solutions",
  "ML Solutions",
  "AI Projects",
  "ML Projects",
  "AI in Healthcare",
  "AI in Finance",
  "AI in Education",
  "AI in Retail",
  "AI in Manufacturing",
  "AI in Marketing",
  "AI in Customer Service",
  "AI in Robotics",
  "AI in Autonomous Vehicles",
  "AI in Cybersecurity",
  "AI in Agriculture",
  "AI in Energy",
  "AI in Entertainment",
  "AI in Gaming",
  "AI in Sports",
  "AI in Real Estate",
  "AI in Supply Chain",
  "AI in Logistics",
  "AI in Human Resources",
  "AI in Legal",
  "AI in Travel",
  "AI in Tourism",
  "AI in Insurance",
  "AI in Telecom",
  "AI in Media",
  "AI in Advertising",
  "AI in E-commerce",
  "AI in Social Media",
  "AI in IoT",
  "AI in Smart Cities",
  "AI in Smart Homes",
  "AI in Wearables",
  "AI in Healthcare Technology",
  "AI in Financial Technology",
  "AI in Educational Technology",
  "AI in Retail Technology",
  "AI in Manufacturing Technology",
  "AI in Marketing Technology",
  "AI in Customer Service Technology",
  "AI in Robotics Technology",
  "AI in Autonomous Vehicles Technology",
  "AI in Cybersecurity Technology",
  "AI in Agriculture Technology",
  "AI in Energy Technology",
  "AI in Entertainment Technology",
  "AI in Gaming Technology",
  "AI in Sports Technology",
  "AI in Real Estate Technology",
  "AI in Supply Chain Technology",
  "AI in Logistics Technology",
  "AI in Human Resources Technology",
  "AI in Legal Technology",
  "AI in Travel Technology",
  "AI in Tourism Technology",
  "AI in Insurance Technology",
  "AI in Telecom Technology",
  "AI in Media Technology",
  "AI in Advertising Technology",
  "AI in E-commerce Technology",
  "AI in Social Media Technology",
  "AI in IoT Technology",
  "AI in Smart Cities Technology",
  "AI in Smart Homes Technology",
  "AI in Wearables Technology",
];